# config/packages/security.yaml
security:
    # ...


    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            anonymous: ~
            # This allows the user to login by submitting a username and password
            # Reference: http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                check_path: security_login

                login_path: security_login

                csrf_token_generator: security.csrf.token_manager
            logout:
                # The route name the user can go to in order to logout
                path: app_logout
                # The name of the route to redirect to after logging out
                target: /
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }