vich_uploader:
    db_driver: orm

    mappings:
        accommodations:
            uri_prefix: /images/accommodations
            upload_destination: '%kernel.project_dir%/public/images/accommodations'
