# config/routes.yaml

index:
    path: /
    controller: App\Controller\MainController::index

app_accommodation_create:
    path: /accommodation
    controller: App\Controller\AccommodationController::create
security_login:
    path: /login
    controller: App\Controller\SecurityController::login
user-new:
    path: /new
    controller: App\Controller\UserController::new
